In [5]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
def get_title_from_index(index):
	return df[df.index == index]["title"].values[0]

def get_index_from_title(title):
	return df[df.title == title]["index"].values[0]

In [9]:
df = pd.read_csv("meta_and_keywords_clean_cut.csv")
df.head(5)

,id,title,Date,Language,Genre,averageRating,numVotes,Keywords,genres_clean,index
0,31186339,The Hunger Games,2012-03-12,"{""/m/02h40lc"": ""English Language""}","{""/m/03btsm8"": ""Action/Adventure"", ""/m/06n90"":...",7.2,834462,"arena, sponsors, tributes, tribute, survivor, ...",Action/Adventure Science Fiction Action Drama,0
1,2231378,The Lemon Drop Kid,1951-03-08,"{""/m/02h40lc"": ""English Language""}","{""/m/06qm3"": ""Screwball comedy"", ""/m/01z4y"": ""...",7.1,1646,"home, money, days, women, scheme, crew, charit...",Screwball comedy Comedy,1
2,595909,A Cry in the Dark,1988-11-03,"{""/m/02h40lc"": ""English Language""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D...",7.4,9,"wife, baby, tent, investigation, sacrifice, wi...",Crime Fiction Drama Docudrama World cinema Cou...,2
3,1952976,Dark Water,2005-06-27,"{""/m/02h40lc"": ""English Language""}","{""/m/01jfsb"": ""Thriller"", ""/m/07s9rl0"": ""Drama...",5.6,59137,"girl, water, apartment, mother, school, daught...",Thriller Drama Horror,3
4,2462689,Meet John Doe,1941-05-03,"{""/m/02h40lc"": ""English Language""}","{""/m/06cvj"": ""Romantic comedy"", ""/m/0hj3nby"": ...",7.6,11875,"letter, speech, newspaper, editor, suicide, se...",Romantic comedy Media Satire Americana Comedy-...,4

In [ ]:
##Step 2: Select Features

features = ['Keywords','genres_clean']